In [79]:
year = 2025; day = 8

from aocd import get_data, submit
import numpy as np
data = get_data(year=year, day=day)
# data = """162,817,812
# 57,618,57
# 906,360,560
# 592,479,940
# 352,342,300
# 466,668,158
# 542,29,236
# 431,825,988
# 739,650,466
# 52,470,668
# 216,146,977
# 819,987,18
# 117,168,530
# 805,96,715
# 346,949,466
# 970,615,88
# 941,993,340
# 862,61,35
# 984,92,344
# 425,690,689"""
# from helpers.helpers import parse_single_matrix

# data = parse_single_matrix(data)
# H, W = data.shape
data = [line.split(",") for line in data.split("\n")]
data = np.array(data).astype("int")

In [80]:
dist = np.zeros((data.shape[0], data.shape[0]))
for i, a in enumerate(data):
    for j, b in enumerate(data): 
        dist[i, j] = np.linalg.norm(a - b)

In [81]:
close = np.unique(np.sort(dist[dist > 0.]))

In [85]:
adj = np.zeros(dist.shape)

for i in range(1000):
    d = close[i]
    locs = np.where(dist == d)
    assert len(locs) == 2
    adj[locs] = 1

In [90]:
import networkx as nx
G = nx.from_numpy_array(adj)
components = list(nx.connected_components(G))

In [88]:
lens = np.sort([len(c) for c in components])
lens

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        6,  6,  6,  6,  6

In [ ]:
data

In [97]:
data[205]

array([93033, 48303, 13768])

In [98]:
data[515]


array([99659, 41427,   144])

In [99]:
93033*99659


9271575747

In [94]:
adj = np.zeros(dist.shape)

for i in range(10_000):
    d = close[i]
    locs = np.where(dist == d)
    assert len(locs) == 2
    adj[locs] = 1

    # if i % 100 == 0:
    if i > 7800:
        G = nx.from_numpy_array(adj)
        components = list(nx.connected_components(G))
        print(i, len(components), locs)

7801 2 (array([329, 493]), array([493, 329]))
7802 2 (array([440, 537]), array([537, 440]))
7803 2 (array([479, 717]), array([717, 479]))
7804 2 (array([ 43, 503]), array([503,  43]))
7805 2 (array([ 70, 458]), array([458,  70]))
7806 2 (array([695, 911]), array([911, 695]))
7807 2 (array([406, 672]), array([672, 406]))
7808 2 (array([351, 634]), array([634, 351]))
7809 2 (array([907, 941]), array([941, 907]))
7810 2 (array([606, 632]), array([632, 606]))
7811 2 (array([650, 925]), array([925, 650]))
7812 2 (array([315, 925]), array([925, 315]))
7813 2 (array([  5, 513]), array([513,   5]))
7814 2 (array([613, 870]), array([870, 613]))
7815 2 (array([237, 731]), array([731, 237]))
7816 2 (array([651, 720]), array([720, 651]))
7817 2 (array([312, 637]), array([637, 312]))
7818 2 (array([641, 850]), array([850, 641]))
7819 2 (array([191, 223]), array([223, 191]))
7820 2 (array([395, 689]), array([689, 395]))
7821 2 (array([545, 634]), array([634, 545]))
7822 2 (array([203, 298]), array([

KeyboardInterrupt: 

In [89]:
np.prod(lens[-3:])


np.int64(122636)

In [ ]:
# wrong
#64# 

In [ ]:
np.prod([:3])

np.int64(1)

In [41]:
locs

(array([ 6, 15]), array([15,  6]))

In [31]:
np.where(dist == np.min(dist[dist > 0.]))

(array([ 0, 19]), array([19,  0]))

In [40]:
tachs = {np.where(data[0, :] == "S")[0][0]}
splits = 0
for y in range(1, len(data)): 
    new_tachs = set()
    for x in tachs: 
        if data[y, x] == "^":
            splits += 1
            if x-1 > 0:
                new_tachs.add(x-1)
            if x+1 <= W:
                new_tachs.add(x+1)
        else:
            new_tachs.add(x)
    tachs = new_tachs
splits


1598

In [41]:
from collections import defaultdict
tachs = {
    np.where(data[0, :] == "S")[0][0]: 1
    }
splits = 0
for y in range(1, len(data)): 
    new_tachs = defaultdict(int)
    for x, count in tachs.items(): 
        if data[y, x] == "^":
            splits += 1
            if x-1 >= 0:
                new_tachs[x-1] += count
            if x+1 < W:
                new_tachs[x+1] += count
        else:
            new_tachs[x] += count
    tachs = new_tachs
ans1 = splits
ans2 = sum(tachs.values())
ans1, ans2


(1598, 4509723641302)

In [42]:
submit(ans1, part="a", year=year, day=day)


Part a already solved with same answer: 1598


In [43]:
submit(ans2, part="b", year=year, day=day)

Part b already solved with same answer: 4509723641302
