In [1]:
year = 2024; day = 2

In [7]:
from aocd import get_data, submit
import numpy as np
data = get_data(year=year, day=day)
data = data.strip()
data = data.split("\n")
data = [np.array([int(d) for d in line.split()]) for line in data]
data[:5]

diff = [np.diff(l) for l in data]

diff[:5]

[array([ 2,  1,  2,  1,  1,  2, -3]),
 array([3, 1, 3, 0]),
 array([1, 3, 3, 2, 2, 4]),
 array([3, 3, 1, 7]),
 array([ 3,  2,  1, -1,  1])]

In [3]:

# [int(np.abs(np.sum(np.sign(np.diff(l))))) for l in data]
def is_valid(d):
    return (
    (np.all(d >=  1) or np.all(d <=  -1)) and
    (np.all(np.abs(d) <= 3))
    )

valid = [is_valid(d) for d in diff]

In [4]:
submit(sum(valid), part="a", year=year, day=day)

coerced int64 value np.int64(663) for 2024/02 to '663'


Part a already solved with same answer: 663


In [5]:
valid_count = 0
for d in data:
    # remove one element from d
    for i in range(0, len(d)):
        x = np.delete(d, i)
        x = np.diff(x)
        if is_valid(x):
            valid_count += 1
            break
valid_count

692

In [6]:
submit(valid_count, part="b", year=year, day=day)

aocd will not submit that answer again. At 2024-12-02 00:26:38.767568-05:00 you've previously submitted 692 and the server responded with:
That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 2! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
